### ISSUE TITLE
Implementación Registro, Modificación y Listado de DueñoAdoptivo

### ISSUE THREAD

**Issue by josdurgar1** [gii-is-DP1/dp1-2020-g1-04#30]
- [x] Creación Entidad Dueño Adoptivo

- [x] Registro de Dueño Adoptivo

- [x] Edición de Dueño Adoptivo

- [x] Listado de Dueños Adoptivos

- [x] Verificación

**Comment by educielan** [comment]
Se encuentra una fallo a la hora de hacer el update del perfil de dueño adoptivo. Esto habrá que corregir para el sprint 2
